package com.attey.governor.core

import android.content.Context
import java.io.File
import java.util.Locale
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

/** Builds a Magisk/KernelSU module that applies a profile after late vendor init. */
object MagiskModule {

    private const val BOOT_DELAY_SECONDS = 45

    fun generate(context: Context, model: DeviceModel, profile: Profile): File {
        val safeName = profile.name.lowercase(Locale.ROOT)
            .replace(Regex("[^a-z0-9_-]"), "_")
            .trim('_')
            .take(48)
            .ifEmpty { "profile" }
        val displayName = profile.name.replace(Regex("[\\r\\n]"), " ").trim().take(80)
        // External app storage can be unavailable before it is mounted.
        val base = context.getExternalFilesDir(null) ?: context.filesDir
        val dir = File(base, "modules").apply { check(isDirectory || mkdirs()) }
        val out = File(dir, "governor-$safeName.zip")

        val prop = """
            id=governor_$safeName
            name=Governor: $displayName
            version=1.0
            versionCode=1
            author=Governor
            description=Re-applies the "$displayName" profile ${BOOT_DELAY_SECONDS}s after boot, once vendor init has stopped overwriting cpufreq.
        """.trimIndent() + "\n"

        val service = buildString {
            appendLine("#!/system/bin/sh")
            appendLine("# Generated by Governor. Applies the \"$displayName\" profile.")
            appendLine("#")
            appendLine("# The sleep is required, not defensive: vendor init and the thermal")
            appendLine("# daemon start late and will overwrite anything written before they do.")
            appendLine("sleep $BOOT_DELAY_SECONDS")
            appendLine()
            append(ProfileEngine.toShellScript(model, profile))
        }

        ZipOutputStream(out.outputStream().buffered()).use { zip ->
            zip.entry("module.prop", prop)
            zip.entry("service.sh", service)
            zip.entry("customize.sh", "#!/system/bin/sh\nSKIPUNZIP=0\n")
            zip.entry("META-INF/com/google/android/update-binary", UPDATE_BINARY)
            zip.entry("META-INF/com/google/android/updater-script", "#MAGISK\n")
        }
        return out
    }

    /** Installer entry point shared by Magisk, KernelSU, and APatch. */
    private val UPDATE_BINARY = """
        #!/sbin/sh
        umask 022
        ui_print() { echo "${'$'}1"; }
        require_new_magisk() {
          ui_print "*******************************"
          ui_print " Please install Magisk v20.4+! "
          ui_print "*******************************"
          exit 1
        }
        OUTFD=${'$'}2
        ZIPFILE=${'$'}3
        mount /data 2>/dev/null
        [ -f /data/adb/magisk/util_functions.sh ] || require_new_magisk
        . /data/adb/magisk/util_functions.sh
        [ "${'$'}MAGISK_VER_CODE" -lt 20400 ] && require_new_magisk
        install_module
        exit 0
    """.trimIndent() + "\n"

    private fun ZipOutputStream.entry(name: String, content: String) {
        putNextEntry(ZipEntry(name))
        write(content.toByteArray())
        closeEntry()
    }
}
