package com.attey.governor.core

import android.content.Context
import java.io.File
import java.util.Locale
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

/**
 * Writes a flashable Magisk/KernelSU module that re-applies a profile at boot.
 *
 * The 45-second delay is not caution, it is the measured requirement. Vendor
 * init and the userspace thermal daemon come up late and overwrite cpufreq
 * settings written during early boot; a module without the delay looks like it
 * did nothing, which is exactly how an evening went in the alioth-perf work.
 */
object MagiskModule {

    private const val BOOT_DELAY_SECONDS = 45

    fun generate(context: Context, model: DeviceModel, profile: Profile): File {
        val safeName = profile.name.lowercase(Locale.ROOT).replace(Regex("[^a-z0-9_-]"), "_")
        // Falls back to internal storage: getExternalFilesDir returns null while
        // external storage is unmounted, and File(null, name) would quietly write
        // a relative path into the process's working directory.
        val dir = context.getExternalFilesDir(null) ?: context.filesDir
        val out = File(dir, "governor-$safeName.zip")

        val prop = """
            id=governor_$safeName
            name=Governor: ${profile.name}
            version=1.0
            versionCode=1
            author=Governor
            description=Re-applies the "${profile.name}" profile ${BOOT_DELAY_SECONDS}s after boot, once vendor init has stopped overwriting cpufreq.
        """.trimIndent() + "\n"

        val service = buildString {
            appendLine("#!/system/bin/sh")
            appendLine("# Generated by Governor. Applies the \"${profile.name}\" profile.")
            appendLine("#")
            appendLine("# The sleep is required, not defensive: vendor init and the thermal")
            appendLine("# daemon start late and will overwrite anything written before they do.")
            appendLine("sleep $BOOT_DELAY_SECONDS")
            appendLine()
            append(ProfileEngine.toShellScript(model, profile))
        }

        ZipOutputStream(out.outputStream().buffered()).use { zip ->
            zip.entry("module.prop", prop)
            zip.entry("service.sh", service)
            // Present so Magisk's installer has something to source; the real work
            // is in service.sh, which runs late enough to survive.
            zip.entry("customize.sh", "#!/system/bin/sh\nSKIPUNZIP=0\n")
            zip.entry("META-INF/com/google/android/update-binary", UPDATE_BINARY)
            zip.entry("META-INF/com/google/android/updater-script", "#MAGISK\n")
        }
        return out
    }

    /**
     * The stock Magisk installer stub.
     *
     * Not optional. Both the Magisk app and recovery *execute* this file to
     * install a module -- a zip carrying only module.prop and service.sh is
     * rejected outright, which is a failure the user would only discover at
     * flash time. KernelSU and APatch accept the same stub.
     */
    private val UPDATE_BINARY = """
        #!/sbin/sh
        umask 022
        ui_print() { echo "${'$'}1"; }
        require_new_magisk() {
          ui_print "*******************************"
          ui_print " Please install Magisk v20.4+! "
          ui_print "*******************************"
          exit 1
        }
        OUTFD=${'$'}2
        ZIPFILE=${'$'}3
        mount /data 2>/dev/null
        [ -f /data/adb/magisk/util_functions.sh ] || require_new_magisk
        . /data/adb/magisk/util_functions.sh
        [ "${'$'}MAGISK_VER_CODE" -lt 20400 ] && require_new_magisk
        install_module
        exit 0
    """.trimIndent() + "\n"

    private fun ZipOutputStream.entry(name: String, content: String) {
        putNextEntry(ZipEntry(name))
        write(content.toByteArray())
        closeEntry()
    }
}
